Enable reading charm name from charmcraft.yaml
charmed-kubernetes/pytest-operator pull request #121
Opened 2023-12-12 06:55 UTC by weiiwang01

Charmcraft has been updated to read metadata information directly from the `charmcraft.yaml` file without a separate `metadata.yaml`. Update to `pytest-operator` to read metadata information from `charmcraft.yaml` when required. 

For further details, refer to the pull request https://github.com/canonical/charmcraft/pull/1126.

2023-12-12 09:55 UTC, tonyandrewmeyer requested changes
Thanks! A minor performance/organisation suggestion:

Since `metadata.yaml` is less likely to exist (where the tests run) in the future, I feel it should likely be the fallback, with `craftcraft.yaml` checked first. This is especially the case since we already have to check if `charmcraft.yaml` exists.

So roughly:

```
charmcraft_yaml_exists = charmcraft_path.exists()
if chamrcraft_yaml_exists:
    # get the name
else:
    metadata_parh = ...
    ...
if charmcraft_yaml_exists and layer_path.exists():
    ...
```

2023-12-15 15:01 UTC, weiiwang01 commented
> Thanks! A minor performance/organisation suggestion:
> 
> Since `metadata.yaml` is less likely to exist (where the tests run) in the future, I feel it should likely be the fallback, with `craftcraft.yaml` checked first. This is especially the case since we already have to check if `charmcraft.yaml` exists.
> 
> So roughly:
> 
> ```
> charmcraft_yaml_exists = charmcraft_path.exists()
> if chamrcraft_yaml_exists:
>     # get the name
> else:
>     metadata_parh = ...
>     ...
> if charmcraft_yaml_exists and layer_path.exists():
>     ...
> ```

Gotcha, updated, thanks!

2024-01-03 20:50 UTC, tonyandrewmeyer approved these changes

2024-01-03 20:52 UTC, tonyandrewmeyer commented
> @tonyandrewmeyer can we get another round of review for that one please ? We've another PR requiring it

Looks good to me, but I don't have write access here, so you'll need Adam or someone to review also.

2024-01-17 13:35 UTC, weiiwang01 commented
> > @tonyandrewmeyer can we get another round of review for that one please ? We've another PR requiring it
> 
> Looks good to me, but I don't have write access here, so you'll need Adam or someone to review also.

@addyess could you help to review this pull request? Thanks!

2024-01-17 14:11 UTC, addyess commented
Funny, i was going to come add this this week.  Thanks for beating me to it.

2024-01-17 14:11 UTC, addyess approved these changes
LGTM

2024-01-17 14:11 UTC, merged