fix: adjust OpsTest.tmp_path to avoid os.sep
charmed-kubernetes/pytest-operator pull request #125
Opened 2024-02-20 09:42 UTC by tonyandrewmeyer

When generating the `tmp_path`, ensure that only characters from the model name that are safe for use in paths are used. This particularly covers the case where the model name is in the form `user/name`, like MAAS.

Fixes #123

2024-02-23 18:49 UTC, addyess requested changes
@tonyandrewmeyer looks good -- a few lint issues

2024-02-27 02:00 UTC, tonyandrewmeyer commented
Are there docs somewhere on how to run the tests (locally, not relying on CI)? `tox -e lint` and `tox -e unit` both pass locally, using Python 3.11, but fail in the CI, so I must not be running them correctly. `tox -e integration` fails locally, but with a totally different error to in the CI: `RuntimeError: Missing dependency: charm`.

2024-02-28 03:52 UTC, addyess requested changes
This still looks good. I think the unit tests could be a bit easier to reason about

2024-02-28 03:52 UTC, addyess commented on tests/unit/test_pytest_operator.py
> +
So, that test was kinda confusing to me.  Can we do this:

```suggestion
async def test_tmp_path_with_nonpath_chars(tmp_path_factory, setup_request):
    setup_request.module.__name__ = "user/model"
    ops_test = plugin.OpsTest(setup_request, tmp_path_factory)
    assert ops_test.tmp_path.name.startswith("user_model")
```

2024-02-28 03:53 UTC, addyess commented
> Are there docs somewhere on how to run the tests (locally, not relying on CI)? `tox -e lint` and `tox -e unit` both pass locally, using Python 3.11, but fail in the CI, so I must not be running them correctly. `tox -e integration` fails locally, but with a totally different error to in the CI: `RuntimeError: Missing dependency: charm`.

if you rebase, you'll see the integration tests are likely going to work after merging https://github.com/charmed-kubernetes/pytest-operator/pull/128

2024-10-07 06:58 UTC, dimaqq commented
@tonyandrewmeyer poke if still relevant

2025-06-16 23:44 UTC, tonyandrewmeyer commented
Probably not worth doing this now.

2025-06-16 23:44 UTC, closed without merging