Add destroy-storage command line parameter
charmed-kubernetes/pytest-operator pull request #133
Opened 2024-05-21 19:45 UTC by luissimas

Adds a `--destroy-storage` CLI argument to enable destroying the storage allocated by Juju on the created models. Without this feature, it is not possible to automatically cleanup storage allocated during the test suite as part of the teardown process.

The behavior is opt-in and can be overridden in a per model basis in a way that resembles the `--keep-models` argument behavior. 

Closes #132

2024-08-06 15:50 UTC, luissimas commented
@addyess any comments on this? If you need any changes please let me know.

We've been using those changes for the past few months in our test environment with machine charms in a 3.5.0 Juju controller over an OpenStack cloud and it's been working flawlessly. With that said it'd be great to get this merged and keep following the upstream repository instead of our fork.

2024-08-06 15:56 UTC, addyess requested changes
Only one small change to the pydocs.  It looks nice.  Thanks for updating the reference.md as well

2024-08-06 16:08 UTC, luissimas commented on pytest_operator/plugin.py
> +                                               the storage
Done. Since it's a small change I've amended the commit to keep the history clean

2024-08-07 13:27 UTC, addyess commented
I'll come back and address the failing integration tests.  Thanks for the contribution @luissimas

2024-08-07 13:27 UTC, merged